# Generated by Django 4.2.5 on 2023-11-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappF23', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses_interested',
            field=models.ManyToManyField(blank=True, related_name='interested_students', to='myappF23.course'),
        ),
    ]
