# Generated by Django 4.2.5 on 2023-11-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappF23', '0003_student_courses_interested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses_interested',
        ),
    ]
